### ISSUE TITLE
Will this script be made compatible with TrueNAS SCALE?

### ISSUE THREAD

**Issue by Mannekino** [dak180/FreeNAS-Report#19] opened 2023-02-25 12:52 UTC
Hi,

Are there plans to make a TrueNAS SCALE version of this script?

Thank you!

Kind regards,

Mannekino

**Comment by dak180** [comment] 2023-02-25 14:38
Duplicate of #5. 

See [#6](https://github.com/dak180/FreeNAS-Report/pull/6#issuecomment-1422618352) for details on (an unsupported) way to get it working now.

**Closed as not planned by dak180** 2023-02-25 14:38 UTC
Labels: duplicate
